# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='Admin', max_length=50),
            preserve_default=False,
        ),
    ]
